id: D4747B9B1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:33:08+00:00'
last_modified: '2022-05-29T08:33:23.347325+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    fea8:
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      order: 77
      base_file: fea8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
