id: 33fe7597d506490e9f8b67cd0d5096b8
initial_creation_type: ocr
source_metadata:
  volumes:
    ef3d7a0a43384c65b4c17e5a4d29f16a:
      base_file: v076.txt
      image_group_id: I1PD95922
      title: ''
      total_pages: 1517
      volume_number: 77
